AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/LineLength:
  Max: 120

Style/BlockDelimiters:
  EnforcedStyle: semantic

# DragonRuby basic
Style/FrozenStringLiteralComment:
  Enabled: false

Style/RandomWithOffset:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Exclude:
    - game/**/*

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - w
    - h
    - r
    - g
    - b
    - id

Style/GlobalVars:
  AllowedVariables:
    - $gtk
    - $scene
    - $menu

Metrics/MethodLength:
  Exclude:
    - game/tests/**/*

Style/Documentation:
  Exclude:
    - game/tests/**/*
